version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:12

jobs:
  deploy-vercel:
    executor: node
    steps:
      - checkout
      - run:
          name: Install Vercel CLI
          command: yarn add -D vercel
      - run:
          name: Deploy to Vercel
          command: ./node_modules/.bin/vercel --token $VERCEL_TOKEN --confirm ./

workflows:
  develop:
    jobs:
      - deploy-vercel:
          context: app
          filters:
            branches:
              only: master
